name: Deploy to EC2

env:
  EC2_NAME: ec2-13-50-75-182.eu-north-1.compute.amazonaws.com
  APP_NAME: envent_rush_api
  EC2_USER: ubuntu

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copie file to EC2
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r . ${{ env.EC2_USER}}@${{ secrets.EC2_HOST }}:~/apps/${{env.APP_NAME}}

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -t ${{ env.EC2_USER}}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/apps || mkdir ~/apps && cd ~/apps
            sudo docker compose down -rmi || true
            sudo docker compose up -d || true
          EOF
